s3:
  endpoint: "https://<bucket>.fra1.digitaloceanspaces.com"
  bucket: "<bucket>"
  token: "<secretName>"
  key: "<secretKey>"

vault:
  plugin-dir: "/vault/plugins"

plugins:
  plugin1: # <-- filename destination
      version: v3.0.0
      type: secret
      arch:
        amd64: plugin1-v3.0.0-amd64 # <-- filename source
        arm64: plugin1-v3.0.0-arm64 # <-- filename source
  plugin2: # <-- filename destination
      filename: plugin2-v1.2.1-amd64 # <-- filename source
      version: v1.2.1
      type: auth
      arch:
        amd64: plugin2-v1.2.1-amd64 # <-- filename source
        arm64: plugin2-v1.2.1-arm64 # <-- filename source

